encryptionsalt: v1:zO0pddkZoA0=:v1:hlp7Hx47YUxRop24:N5TiLO+BuS/iztR9hVALToSC7FsoKg==

config:
  azure-native:location: AustraliaEast

  infra-iac:mainParams:
    logRetentionDays: 0

  infra-iac:webappParams:
    pricingTier: P0V3 # remember to remove slot first (do 2 deployment, by changing the addSlot to false first) before moving to a lower tier that doenst support slots
    maxCapacity: 1
    minCapacity: 1
    addSlot: True # slot is only available for P0V3 and above, only set this to True after update and run the pricingTier to P0V3 and above

  infra-iac:containerParams:
    avCPU: 1
    avMemory: 1.5

  infra-iac:dbParams:
    coordinatorServerEdition: 'BurstableMemoryOptimized'
    coordinatorStorageQuotaInMb: 32768
    coordinatorVcoreCount: 1
    haEnabled: False
    nodeCount: 0
    nodeStorageQuotaInMb: 524288
    nodeVcores: 4
    shardsOnCoordinatorEnabled: True
