export enum UserReturnStatus {
  SUCCESS = "SUCCESS",
  LOADING = "LOADING",
  NOT_INVITED = "NOT_INVITED",
  NOT_FOUND = "NOT_FOUND",
  UNAUTHORISED = "UNAUTHORISED",
  MULTIPLE_SESSIONS = "MULTIPLE_SESSIONS"
}
