name: Deploy Frontend
on:
  push:
    branches: [dev, prod]
  workflow_dispatch:

jobs:
  deploy:
    name: Placeholder step
    runs-on: opch
    steps:
      - name: 'Placeholder step'
        run: |
          echo Placeholder
